version: 2
mergeable:
  - when: issues.opened
    name: "Test mergeable staging installation"
    validate:
      - do: title
        # Enforce semantic release convention.
        must_include:
          regex: ^(feat|docs|chore|fix|refactor|test|style|perf)(\(\w+\))?:.+$
          message: Semantic release conventions must be follow
    pass:
      - do: comment
        payload:
          body: >
            Hello! I'm the PRODUCTION mergeable bot 🤖! Just wanted to let you I'm able to communicate with GitHub and everything appears to be okay...for now!
