version: 2
mergeable:
  - when: issues.opened
    name: "Test mergeable staging installation"
    validate: []
    pass:
      - do: comment
        payload:
          body: >
            Hello! I'm the PRODUCTION mergeable bot 🤖! This is working here but not in org!!
