---
name: Add User to Bypass Verified Commits Team
description: Template for requesting to add a GitHub user to the "bypass-verified-commits" team
title: 'Add user to bypass-verified-commits team'
labels: ['team-management']
assignees: 
- ccoe-nos
---

## Add User to Bypass Verified Commits Team Request

### Team Information
- **Team Name**: bypass-verified-commits

### User Information
- **GitHub Username**: [GITHUB_USERNAME]

### Reason for Addition
- **Reason**: [REASON_FOR_ADDITION]

### Additional Notes
- [ANY_ADDITIONAL_NOTES]

---

**Instructions:**
1. Replace `[GITHUB_USERNAME]` with the GitHub username of the user to be added.
2. Replace `[REASON_FOR_ADDITION]` with the reason for adding the user to the team.
3. Add any additional notes if necessary.
4. Submit the issue for review.
